### ISSUE TITLE
Где хранить ID пользователей?

### ISSUE THREAD

**Issue by eSlider** [produktor/tezos#3]
Где хранить айдишки юзеров мессенджеров (телега, дискорт). 

В самом смарт контракте или нет? 

> Вообще пишут что это не секьюрно.

**Comment by eSlider** [comment]
@GRyabkin, прочёл что 

> индексатор может быть написан с использованием [Dappetizer](https://dappetizer.dev/), фреймворка для создания индексаторов на Tezos. 
> 
> Dappetizer имеет встроенную поддержку PostgreSQL, который мы рекомендуем для хранения данных.

Мы можем в Dappetizer  хранить айдишки?

**Comment by hrabkin** [comment]
@eSlider я думаю так и надо

**Comment by hrabkin** [comment]
@eSlider то есть на фронте нужна будет форма для ввода айдишки телеги или дискорда, возможно можно через апи этих мессенджеров как-то это сделать, мы думали может ботов написать для этого

**Comment by eSlider** [comment]
@GRyabkin  если писать бота, то его надо где-то хостить? В случае с Dappteizer же наверное нет?

**Comment by eSlider** [comment]
Хотя если вам(нам) так легче, то почему бы и нет.  

Аргумент за бота:  сперва реализовать вариант полегче, и решить общую задачу и после, если останется время будем улушаться. 

В общем я, вначелае, за быстрое решение, если  Dappteizer вообще непонятное и долго разбираться.

**Comment by hrabkin** [comment]
@eSlider ну вообще нам и индексер надо будет задеплоить на сервер и PostregSQL, мы можем все на одном сервере развернуть под разные порты естественно, вопрос в нагрузке, но для демо думаю хватит какого медиум или даже small AWS EC2 инстанса или дроплета на Digital Ocean

**Comment by eSlider** [comment]
@GRyabkin пока вопрос нагрузки не стоит остро LB можно отложить. 
Один инстанс в AWS вполне себе решение, я полагаю.

**Comment by eSlider** [comment]
У вас есть наработки для формирование контейнера, тобишь Dockerfile? 
Можно прям в master-ветку добавить, что-бы все сразу было легче. 
Зборка, деплоймент и релиз в Github-Action CI у меня [есть](https://github.com/eSlider/docker-tippecanoe/runs/3143448755?check_suite_focus=true), если что.

**Comment by diakov312** [comment]
Надо бы обсудить пару моментов с телегой и айди групп, с дискордом надо заресерчить, условно апи телеграмма можно разделить на 2 части насколько я знаю, первое работает с ботами и через него нельзя добалять группы, воторое с клиентом телеграмма и через него можно это делать.

> Сервис синхронизации для добавления или удаления определенных Telegram или Discord-каналов на основе баланса пользователя. 

Вот тут хочу уточнить где должно происходить удаление и добавление групп(в самом телеграмме у юзера и так же в дискорде?). И какие пользователи, для этого будут использоваться(пользователи определенной системы которую пишем сами, или еще кто-то, опять же тогда надо будет связать пользователя телеграмма и дискорда).

Надеюсь не очень много глупых вопросов, но я бы устроил бы созвон завтра вечером и обсудил бы например какраз эти основные моменты, было бы проще понять и задачу и кто что не понимает в ней.

**Comment by diakov312** [comment]
> Yeah, that is wrong description, it meant adding or removing users to/from specified channels, not channels themselves

Да, если правильно понял то нужен бот который будет менеджить участников различных каналов на основе баланса. И то же с дискордом. Но там тоже как всегда может куча нюансов вылезти закрытые или открытые кааналы, каналы или группы, или и то и другое.

**Comment by hrabkin** [comment]
@eSlider темплейта докера нет, но в задании пишут будет бонусом helm charts и kubernetes. Я вообще думал смарт контрактом заняться но могу помочь и на бэке и на фронте.

**Comment by eSlider** [comment]
> Надо бы обсудить пару моментов с телегой и айди групп, с дискордом надо заресерчить, условно апи телеграмма можно разделить на 2 части насколько я знаю, первое работает с ботами и через него нельзя добалять группы, воторое с клиентом телеграмма и через него можно это делать.

Да, давай обсудим в отдельной задаче #6. Вопросы отличные! Созвон отдельно в группе спрошу всех тоже. )

Оставим этот тред на выяснение **где мы будем хранить айдишки**.

**Comment by eSlider** [comment]
> Да, если правильно понял то нужен бот который будет менеджить участников различных каналов на основе баланса. И то же с дискордом. Но там тоже как всегда может куча нюансов вылезти закрытые или открытые кааналы, каналы или группы, или и то и другое.

@diakov312, наверняка! Тоже отдельная тема #7

**Comment by eSlider** [comment]
> @eSlider темплейта докера нет, но в задании пишут будет бонусом helm charts и kubernetes. Я вообще думал смарт контрактом заняться но могу помочь и на бэке и на фронте.

@GRyabkin, точно! Нужно опросить людей в канале. С helm charts не сталкивался, а kubernetes кто-то уже в канале изьявил возможность взять на себя. 

Контракты писать из нас умееешь только ты,  а так-же @AlexKrylovNikiforov в процессе обучения. 

Поможешь описать задачу по смартконтракту так-что бы понять что именно требуется?

**Comment by hrabkin** [comment]
@eSlider ну как минимум нужно определиться будет ли наш токен разменной монетой стандарта F1.2 или уникальным билетом стандарта F2, в случае с проверкой баланса думаю F1.2 достаточно, хотя возможно имелось ввиду проверять баланс к примеру уже существующего токена XT,Z например. А уже второй случай это уникальный "билет" секъюрити токен стандарта F2 который нам нужно создать и минтить для каждого нового регистрируемого в системе юзера. То есть я так полагаю мы можем сделать два условия получения доступа или баланс токенов минимальный на счету (к примеру можно чекать XTZ либо любые другие существующие токены блокчейна Тезос, то есть дать выбрать админу этот критерий) и второй случай это наличие секъюрити токена который администратор может выдать в случае отсутствия достаточно количества токенов на балансе.

Резюме (пока не финальный вариант): 
1) сделать F2 токен и его связь с регистрируемым юзером (возможно сохранение его кошелька в нашей базе, а может привязка токена к юзеру по его айдишке в телеге или дискорде, а может и всю инфу сохранить в storage смарт контракта и искать в блокчейне не кошелек а токен с уникальной айдишкой, пока надо подумать), 

2) минтинг токена по запросу админа, и сохранение в storage необходимой для таска инфы. Возможно у токена будет дата экспирации, некий интервал временной, или он будет списываться после добавления юзера в канал и подавать заново запрос.

**Comment by hrabkin** [comment]
@eSlider это issue можно закрывать, я сегодня пришел к выводу что эти айди вообще возможно нигде не нужно хранить. Будет привязка к кошельку в блокчейне Тезос

**Comment by eSlider** [comment]
@GRyabkin, отлично!
